apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default   #CHANGE if you use another namespace
data:
  nginx.conf: |
    #COPY the FULL nginx.conf content here
    # This file is mounted directly as /etc/nginx/nginx.conf
