apiVersion: v1
kind: Service
metadata:
  name: nginx-log-ingestion
  namespace: default
  annotations:
    #OPTIONAL: make it internal instead of public
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer   # âœ… AKS creates Azure Load Balancer
  selector:
    app: nginx-log-ingestion
  ports:
  - name: https
    port: 443           # Public port
    targetPort: 443     # Container port
